//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAC
    {
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string ARC_MODEL_KODU { get; set; }
        public Nullable<short> ARC_MODEL_TRH { get; set; }
        public string CARI_KOD { get; set; }
        public string PLAKA { get; set; }
        public string DEPO_KODU { get; set; }
        public string BARKODU { get; set; }
        public string OZEL { get; set; }
        public Nullable<double> ATF { get; set; }
        public Nullable<double> KDV_SIZ { get; set; }
        public Nullable<double> KDV { get; set; }
        public string EKTAVPRM { get; set; }
        public string SPOR { get; set; }
        public string KULL_SEKLI { get; set; }
        public string TARIFE_NO { get; set; }
        public string ARC_RENK_KODU { get; set; }
        public Nullable<System.DateTime> GARANTI_BAS { get; set; }
        public Nullable<System.DateTime> GARANTI_BIT { get; set; }
        public string GAR_SERI_NO1 { get; set; }
        public string GAR_SERI_NO2 { get; set; }
        public Nullable<double> GARANTI_PUANI { get; set; }
        public Nullable<double> GARANTI_KALAN_PUANI { get; set; }
        public string FATURA_NO { get; set; }
        public Nullable<System.DateTime> FAT_TRH { get; set; }
        public Nullable<System.DateTime> SIP_TRH { get; set; }
        public string SIP_NO { get; set; }
        public Nullable<System.DateTime> AL_FAT_TRH { get; set; }
        public string ALIS_FAT_NO { get; set; }
        public Nullable<double> BSATIS_NO { get; set; }
        public string ANAHTAR_NO { get; set; }
        public string FIKTIF { get; set; }
        public Nullable<double> YP_YUZDE { get; set; }
        public Nullable<short> KAMPANYA { get; set; }
        public string ARAC_TIP { get; set; }
        public string NOTLAR { get; set; }
        public string BAYI_KOD { get; set; }
        public Nullable<double> OTV { get; set; }
        public Nullable<double> ARAC_BEDEL { get; set; }
        public Nullable<double> OTV_TUT { get; set; }
        public Nullable<double> OTV_IST { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public Nullable<double> MAS_TOP { get; set; }
        public Nullable<System.DateTime> SGBASTRH { get; set; }
        public Nullable<System.DateTime> SGBITRH { get; set; }
        public Nullable<System.DateTime> MUAYENE_TRH { get; set; }
        public Nullable<System.DateTime> EKSOZ_TRH { get; set; }
        public Nullable<System.DateTime> KASKA_TRH { get; set; }
        public string OTPA { get; set; }
        public Nullable<System.DateTime> TRF_CIKIS_TRH { get; set; }
        public string IC_RENK { get; set; }
        public string AKTIF { get; set; }
        public Nullable<double> KIRA_FYT_SAAT { get; set; }
        public Nullable<double> KIRA_FYT_GUN { get; set; }
        public Nullable<double> KIRA_FYT_HAFTA { get; set; }
        public Nullable<double> KIRA_FYT_AY { get; set; }
        public Nullable<double> KIRA_FYT_YIL { get; set; }
        public Nullable<double> GEC_FAIZ_SAAT { get; set; }
        public Nullable<double> GEC_FAIZ_GUN { get; set; }
        public Nullable<double> GEC_FAIZ_HAFTA { get; set; }
        public Nullable<double> GEC_FAIZ_AY { get; set; }
        public Nullable<System.DateTime> EKSOZ_BITTRH { get; set; }
        public Nullable<System.DateTime> MUAYENE_BITTRH { get; set; }
        public Nullable<System.DateTime> KASKO_BITTRH { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<double> MALIYET_FYT_TL { get; set; }
        public string SANZIMAN_NO { get; set; }
        public Nullable<int> EK_GARANTIGUN { get; set; }
        public string STATU1 { get; set; }
        public string STATU2 { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string RUHSAT_SERINO { get; set; }
        public string PER_KOD_ZIMMET { get; set; }
        public string PER_ADI_ZIMMET { get; set; }
        public Nullable<System.DateTime> K2BAS_TRH { get; set; }
        public Nullable<System.DateTime> K2BIT_TRH { get; set; }
        public Nullable<decimal> K2BELGE_TUTAR { get; set; }
        public Nullable<decimal> YAKIT_LIMIT_LT { get; set; }
        public Nullable<decimal> YAKIT_LIMIT_TUTAR { get; set; }
        public string RUHSAT_SINIF { get; set; }
        public string HGS_SINIF { get; set; }
        public string HGS_NO { get; set; }
        public string TTS_DURUM { get; set; }
        public string TTS_CIHAZTIP { get; set; }
        public string GPS_DURUM { get; set; }
        public Nullable<double> SATIS_BEDEL { get; set; }
        public string K2_DURUM { get; set; }
        public int ID { get; set; }
    }
}
