//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI
    {
        public string CARI_KOD { get; set; }
        public string FIRMA_ADI { get; set; }
        public string YETKILI_ADI { get; set; }
        public string YETKILI_SOYAD { get; set; }
        public string ADRES_1 { get; set; }
        public string ADRES_2 { get; set; }
        public string PK { get; set; }
        public string SEMT { get; set; }
        public string ILI { get; set; }
        public string ULKE { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string FAKS { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string MESLEK_KOD { get; set; }
        public string VD { get; set; }
        public string VN { get; set; }
        public string CINSIYET { get; set; }
        public string BANKA_1 { get; set; }
        public string BANKA_2 { get; set; }
        public Nullable<double> SERMAYE { get; set; }
        public Nullable<double> TEMINAT_1 { get; set; }
        public Nullable<double> TEMINAT_2 { get; set; }
        public string TEM_BANK_1 { get; set; }
        public string TEM_BANK_2 { get; set; }
        public string CARI_GRP_KOD { get; set; }
        public Nullable<double> RISK_LIMITI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<short> IND_YUZ_PAR { get; set; }
        public Nullable<short> IND_YUZ_AKS { get; set; }
        public Nullable<short> IND_YUZ_SRF { get; set; }
        public Nullable<short> IND_YUZ_ISCI { get; set; }
        public Nullable<short> IND_YUZ_HSR { get; set; }
        public Nullable<short> IND_YUZ_BKM { get; set; }
        public Nullable<short> IND_YUZ_ARZ { get; set; }
        public string DOVIZ { get; set; }
        public string BABA_ADI { get; set; }
        public string DOGUM_YERI { get; set; }
        public string DOGUM_YIL { get; set; }
        public Nullable<System.DateTime> DOGUM_TRH { get; set; }
        public string MUH_KOD { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<short> VADEGUN { get; set; }
        public string SIGORTA { get; set; }
        public string ILETISIM_YOK { get; set; }
        public string TEL4 { get; set; }
        public string KIMLIKNO { get; set; }
        public Nullable<double> PMNO { get; set; }
        public string FIRMA_ADI2 { get; set; }
        public string OZEL_KOD_1 { get; set; }
        public string OZEL_KOD_2 { get; set; }
        public string OZEL_KOD_3 { get; set; }
        public string PER_KOD { get; set; }
        public string TAH_SEKLI { get; set; }
        public Nullable<System.DateTime> KAYIT_TRH { get; set; }
        public string MERKEZ_BAYI { get; set; }
        public string ANA_ADI { get; set; }
        public string N_SERI { get; set; }
        public string N_NO { get; set; }
        public string N_IL { get; set; }
        public string N_ILCE { get; set; }
        public string N_CILTNO { get; set; }
        public string N_AILESIRANO { get; set; }
        public string N_SIRANO { get; set; }
        public string KANGRUBU { get; set; }
        public string EHL_VER_YER { get; set; }
        public Nullable<System.DateTime> EHL_VER_TRH { get; set; }
        public string EHL_NO { get; set; }
        public string EHL_SINIF { get; set; }
        public string EHL_ACIKLAMA { get; set; }
        public string PSP_VER_YER { get; set; }
        public Nullable<System.DateTime> PSP_VER_TRH { get; set; }
        public string PSP_NO { get; set; }
        public string PSP_ACIKLAMA { get; set; }
        public Nullable<short> WEB_AKTAR { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string EF_UNVAN { get; set; }
        public string SOKAK { get; set; }
        public string KAPI_NO { get; set; }
        public string DAIRE_NO { get; set; }
        public Nullable<byte> EF_MUKELLEF { get; set; }
        public Nullable<byte> EI_MUKELLEF { get; set; }
        public string ENT_KOD { get; set; }
        public string VERSIP_VAR { get; set; }
    }
}
