//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISEAYRIN
    {
        public string ISEMRI_NO { get; set; }
        public string TIP { get; set; }
        public Nullable<short> SIRANO { get; set; }
        public Nullable<double> STOK_NO { get; set; }
        public string YEDEK_P_ADI { get; set; }
        public string STOK_KOD_NO { get; set; }
        public Nullable<double> STOK_MIKTAR { get; set; }
        public Nullable<double> VERILEN_MIKTAR { get; set; }
        public Nullable<double> TESLIM_MIKTAR { get; set; }
        public Nullable<double> STOK_FIYATI { get; set; }
        public Nullable<double> FYT_USD { get; set; }
        public Nullable<double> KDV { get; set; }
        public string GARANTI_TIPI { get; set; }
        public string ISLEM_ACIKLAMASI { get; set; }
        public string CLAIM_TURU { get; set; }
        public string ARIZA_KODU { get; set; }
        public string S { get; set; }
        public string EXP { get; set; }
        public Nullable<System.DateTime> TESLIM_TRH { get; set; }
        public Nullable<double> FATURANO { get; set; }
        public Nullable<double> CLAIMNO { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<short> FYILI { get; set; }
        public string DEPO_KODU { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<double> PAKETNO { get; set; }
        public Nullable<int> KAMPNO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<double> GRUP_DEGER { get; set; }
        public string SERINO { get; set; }
        public Nullable<short> ISC_SIRANO { get; set; }
        public int ID { get; set; }
    }
}
