//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISEMRI
    {
        public string IS_EMRI_NO { get; set; }
        public string IE_TIP { get; set; }
        public string SERVIS_KOD { get; set; }
        public string IS_ENO { get; set; }
        public string CARI_KOD { get; set; }
        public string ARAC_TIP { get; set; }
        public string ARAC_MODEL { get; set; }
        public string SASI_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<System.DateTime> TESLIM_TRH { get; set; }
        public string RENK_KOD { get; set; }
        public string PLAKA_NO { get; set; }
        public string GARANTI_NO { get; set; }
        public Nullable<System.DateTime> ARAC_GIRIS_TRH { get; set; }
        public Nullable<System.DateTime> ARAC_GIRIS_SAAT { get; set; }
        public Nullable<System.DateTime> TAHMINI_TES_TRH { get; set; }
        public Nullable<System.DateTime> TAH_TES_SAAT { get; set; }
        public Nullable<bool> VURUK { get; set; }
        public Nullable<bool> CIZIK { get; set; }
        public Nullable<bool> PAS { get; set; }
        public Nullable<bool> BOYA_HATA { get; set; }
        public Nullable<double> PDI_TUTAR { get; set; }
        public Nullable<double> HASAR_TUTAR { get; set; }
        public Nullable<double> ARIZA_TUTAR { get; set; }
        public Nullable<double> PDI_IS_TUTAR { get; set; }
        public Nullable<double> ARZ_IS_TUTAR { get; set; }
        public Nullable<double> HASAR_IS_TUTAR { get; set; }
        public Nullable<double> PAR_TOP_TUTAR { get; set; }
        public Nullable<double> IS_TOP_TUTAR { get; set; }
        public Nullable<double> TOP_TUTAR { get; set; }
        public Nullable<System.DateTime> GARANTI_BITIS { get; set; }
        public string DEPO_YAP { get; set; }
        public string DISPOZ_YAP { get; set; }
        public string KAPANDI { get; set; }
        public Nullable<short> AY { get; set; }
        public Nullable<short> YIL { get; set; }
        public string MUSTALIM_1 { get; set; }
        public string MUSTALIM_2 { get; set; }
        public string MUSTALIM_3 { get; set; }
        public string MUSTALIM_4 { get; set; }
        public string MUSTALIM_5 { get; set; }
        public string MUSTALIM_6 { get; set; }
        public string MUSTALIM_7 { get; set; }
        public string MUSTALIM_8 { get; set; }
        public string MUSTALIM_9 { get; set; }
        public string MUSTALIM_10 { get; set; }
        public string GENEL_DUR { get; set; }
        public Nullable<bool> CAKMAK { get; set; }
        public Nullable<bool> RADYO_TEYP { get; set; }
        public Nullable<bool> AVADANLIK { get; set; }
        public Nullable<bool> KRIKO { get; set; }
        public Nullable<bool> RUHSAT { get; set; }
        public Nullable<bool> STEPNE { get; set; }
        public string DIGER_EMANET { get; set; }
        public string YAKIT_MIK { get; set; }
        public string ARAC_TESLIM_ALAN { get; set; }
        public string YP_TESLIM_ALAN { get; set; }
        public string S { get; set; }
        public Nullable<double> GARANTI_PUANI { get; set; }
        public Nullable<double> GARANTI_KALAN_PUANI { get; set; }
        public Nullable<double> IE_GAR_HARCA_PUAN { get; set; }
        public string TEKRAR { get; set; }
        public string YABANCI_ARAC { get; set; }
        public Nullable<short> KAMPANYA { get; set; }
        public string IPTAL { get; set; }
        public string AKTARILDI { get; set; }
        public string TESLIM_EDEN { get; set; }
        public Nullable<double> KAMPIE_NO { get; set; }
        public Nullable<double> TEKLIF_NO { get; set; }
        public Nullable<short> FYILI { get; set; }
        public string TESLIM_ED_TEL { get; set; }
        public Nullable<double> PAR_ISK { get; set; }
        public Nullable<double> ISC_ISK { get; set; }
        public Nullable<double> GAR_TUT { get; set; }
        public Nullable<double> ARA_TUT { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public Nullable<double> NET_TUT { get; set; }
        public string HASAR { get; set; }
        public string IC_RENK { get; set; }
        public string KULLANIM_SEKLI { get; set; }
        public string YPTESLIMEDEN { get; set; }
        public string SIGORTA { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<byte> KAPANIS_DOK { get; set; }
        public string KAPANIS_NOTU { get; set; }
        public string IE_ALTTIP { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<System.DateTime> ARIZA_BTRH { get; set; }
        public string HASAR_DURUM { get; set; }
        public Nullable<byte> DIGER1 { get; set; }
        public Nullable<double> LD_SOL_ON { get; set; }
        public Nullable<double> LD_SOL_ARKA { get; set; }
        public Nullable<double> LD_SAG_ON { get; set; }
        public Nullable<double> LD_SAG_ARKA { get; set; }
        public string ACIKLAMA { get; set; }
        public string TAHMINI_ISLER_1 { get; set; }
        public string TAHMINI_ISLER_2 { get; set; }
        public string TAHMINI_ISLER_3 { get; set; }
        public string TAHMINI_ISLER_4 { get; set; }
        public string TAHMINI_ISLER_5 { get; set; }
        public string TAHMINI_ISLER_6 { get; set; }
        public string TAHMINI_ISLER_7 { get; set; }
        public Nullable<double> TAHMINI_YP_TUT { get; set; }
        public Nullable<double> TAHMINI_ISC_TUT { get; set; }
        public Nullable<double> TAHMINI_KDVLI_TUT { get; set; }
        public Nullable<double> TAHMINI_KDVSIZ_TUT { get; set; }
        public Nullable<byte> ONARIM_BELGE { get; set; }
        public Nullable<System.DateTime> CIKIS_TRH { get; set; }
        public Nullable<System.DateTime> TTT { get; set; }
        public string ATOLYE { get; set; }
        public string DURUM { get; set; }
        public string TESLIM_ALAN2 { get; set; }
        public Nullable<byte> KM_RESET { get; set; }
        public Nullable<int> PLANID_1 { get; set; }
        public Nullable<int> PLANID_2 { get; set; }
        public Nullable<int> PLANID_3 { get; set; }
        public Nullable<int> PLANID_4 { get; set; }
        public Nullable<int> PLANID_5 { get; set; }
        public Nullable<int> PLANID_6 { get; set; }
        public Nullable<int> PLANID_7 { get; set; }
        public Nullable<int> PLANID_8 { get; set; }
        public Nullable<int> PLANID_9 { get; set; }
        public Nullable<int> PLANID_10 { get; set; }
        public Nullable<byte> MUSOK_1 { get; set; }
        public Nullable<byte> MUSOK_2 { get; set; }
        public Nullable<byte> MUSOK_3 { get; set; }
        public Nullable<byte> MUSOK_4 { get; set; }
        public Nullable<byte> MUSOK_5 { get; set; }
        public Nullable<byte> MUSOK_6 { get; set; }
        public Nullable<byte> MUSOK_7 { get; set; }
        public Nullable<byte> MUSOK_8 { get; set; }
        public Nullable<byte> MUSOK_9 { get; set; }
        public Nullable<byte> MUSOK_10 { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public Nullable<short> SUBEKODU2 { get; set; }
        public Nullable<double> IPNO { get; set; }
        public string IKAME_PLAKA { get; set; }
        public Nullable<double> LD_SAG_ARKAIC { get; set; }
        public Nullable<double> LD_SOL_ARKAIC { get; set; }
        public int ID { get; set; }
    }
}
