//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class EROTO2020Entities : DbContext
    {
        public EROTO2020Entities()
            : base("name=EROTO2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARAC> ARAC { get; set; }
        public virtual DbSet<CARI> CARI { get; set; }
        public virtual DbSet<ISEAYRIN> ISEAYRIN { get; set; }
        public virtual DbSet<ISEMRI> ISEMRI { get; set; }
        public virtual DbSet<MODEL> MODEL { get; set; }
        public virtual DbSet<STOK> STOK { get; set; }

        internal DataTable DataTable(IQueryable<object> queryables)
        {
            throw new NotImplementedException();
        }
    }
}
