//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL
    {
        public string ARC_MODEL_KODU { get; set; }
        public string ARC_MODEL_ADI { get; set; }
        public string MARKA { get; set; }
        public string MODEL1 { get; set; }
        public string CINS { get; set; }
        public string ARC_SERI { get; set; }
        public string MOTOR_TIP { get; set; }
        public string MOTOR_SILIN_SAY { get; set; }
        public string MOTOR_HACIM { get; set; }
        public Nullable<short> MOTOR_GUC { get; set; }
        public string VITES { get; set; }
        public Nullable<short> AGIRLIK { get; set; }
        public string GOVDE_TIP { get; set; }
        public string TRIM_TIP { get; set; }
        public Nullable<short> BOY { get; set; }
        public Nullable<short> EN { get; set; }
        public Nullable<short> YUKSEKLIK { get; set; }
        public string SANZIMAN_TIPI { get; set; }
        public string AKSESUAR { get; set; }
        public string SIPARIS_SEV { get; set; }
        public string MIN_STOK_SEV { get; set; }
        public string MAX_STOK_SEV { get; set; }
        public Nullable<short> SIPARIS_SURESI { get; set; }
        public string ISKONTO_GRP { get; set; }
        public Nullable<double> D_BASI_STK_MIK { get; set; }
        public Nullable<double> D_BASI_STK_DEGERI { get; set; }
        public Nullable<double> MALIYET_FYT_TL { get; set; }
        public Nullable<double> MALIYET_FYT_USD { get; set; }
        public Nullable<double> MALIYET_FYT_DOVIZ { get; set; }
        public Nullable<double> SATIS_FIYAT_TL { get; set; }
        public Nullable<double> SATIS_FIYAT_USD { get; set; }
        public Nullable<double> SATIS_FIYAT_DOVIZ { get; set; }
        public Nullable<double> ALISFIYAT_TL { get; set; }
        public Nullable<double> ALISFIYAT_USD { get; set; }
        public Nullable<double> ALISFIYAT_DOVIZ { get; set; }
        public string FYT_KUR { get; set; }
        public Nullable<double> KAR_ORANI { get; set; }
        public Nullable<double> VERGILER { get; set; }
        public Nullable<bool> RADYO_TEYP { get; set; }
        public Nullable<bool> CAKMAK { get; set; }
        public Nullable<bool> AVANDANLIK { get; set; }
        public Nullable<bool> KRIKO { get; set; }
        public Nullable<bool> STEPNE { get; set; }
        public Nullable<bool> RUHSAT { get; set; }
        public Nullable<double> KDV { get; set; }
        public string YAKIT_TIPI { get; set; }
        public byte[] RESIM { get; set; }
        public string OTURMA_YERI { get; set; }
        public string TAV_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string CAP { get; set; }
        public Nullable<bool> SIP_VERILEBILIR { get; set; }
        public string OZEL1 { get; set; }
        public string OZEL2 { get; set; }
        public string MUH_S { get; set; }
        public string MUH_IADE_S { get; set; }
        public string MUH_ISK_S { get; set; }
        public string MUH_KDV_S { get; set; }
        public string MUH_A { get; set; }
        public string MUH_IADE_A { get; set; }
        public string MUH_ISK_A { get; set; }
        public string MUH_KDV_A { get; set; }
        public string AKTARMA { get; set; }
        public Nullable<short> SUBAP_ADET { get; set; }
        public Nullable<double> YAKIT_TUK1 { get; set; }
        public Nullable<double> YAKIT_TUK2 { get; set; }
        public Nullable<double> DEPO_HACIM { get; set; }
        public Nullable<double> BAGAJ_HACIM { get; set; }
        public string KATALITIK { get; set; }
        public string CLAIM_ARCTIP { get; set; }
        public Nullable<double> OTV { get; set; }
        public string MUH_OTV_A { get; set; }
        public string MUH_OTV_S { get; set; }
        public bool POQ_VER { get; set; }
        public string NETAGIR { get; set; }
        public string ISTIHAD { get; set; }
        public string AZAMIAGR { get; set; }
        public string KAPASITE { get; set; }
        public string DINGIL { get; set; }
        public string TEKERLEK { get; set; }
        public string KAVRAMA { get; set; }
        public string YEDEK1 { get; set; }
        public string YEDEK2 { get; set; }
        public string YEDEK3 { get; set; }
        public string YEDEK4 { get; set; }
        public string YEDEK5 { get; set; }
        public string TEK_ADET { get; set; }
        public string ARAC_GRUP { get; set; }
        public string SINIFI { get; set; }
        public string TIP_ONAYNO { get; set; }
        public string AZAMI_YUKLU_KUTLE { get; set; }
        public string KATAR_YUKLU_KUTLE { get; set; }
        public Nullable<decimal> MBAK_PER_KM { get; set; }
        public int ID { get; set; }
    }
}
