//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomotivServisYazilimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK
    {
        public double STOK_NO { get; set; }
        public string STOK_ADI_TR { get; set; }
        public string STOK_ADI_ING { get; set; }
        public string BARKOD { get; set; }
        public string BARK_TIP { get; set; }
        public string STOK_KOD_NO { get; set; }
        public Nullable<System.DateTime> ACILIS_TRH { get; set; }
        public string GRUP_NO { get; set; }
        public string PNC_NO { get; set; }
        public string PNCSUBNO { get; set; }
        public string BIRIMI { get; set; }
        public Nullable<double> KRITIK_SEV { get; set; }
        public Nullable<double> SIPARIS_SEV { get; set; }
        public Nullable<double> HEDEF_SEV { get; set; }
        public Nullable<System.DateTime> FYT_TRH { get; set; }
        public Nullable<double> ALIS_FYT_TL { get; set; }
        public Nullable<double> ALIS_FYT_USD { get; set; }
        public Nullable<double> ALIS_FYT_DOVIZ { get; set; }
        public Nullable<double> SAT_FYT_TL { get; set; }
        public Nullable<double> SAT_FYT_USD { get; set; }
        public Nullable<double> SAT_FYT_DOVIZ { get; set; }
        public string FYT_KUR { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<double> SIPARIS_SURESI { get; set; }
        public Nullable<int> ISKONTO_GRP { get; set; }
        public Nullable<double> VERGILER { get; set; }
        public Nullable<double> MALIYET_FYT_TL { get; set; }
        public Nullable<double> MALIYET_FYT_USD { get; set; }
        public Nullable<double> MALIYET_FYT_DOVIZ { get; set; }
        public Nullable<double> KAR_ORAN { get; set; }
        public string AMBALAJ_NO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<short> RESIM_NO { get; set; }
        public Nullable<short> KOORX { get; set; }
        public Nullable<short> KOORY { get; set; }
        public string ESKI_PART_NO { get; set; }
        public string KAYNAK { get; set; }
        public Nullable<int> ETIKET { get; set; }
        public string WIRACC0 { get; set; }
        public string WIRACC1 { get; set; }
        public string WIRATD { get; set; }
        public string PUTRA { get; set; }
        public string SATRIA { get; set; }
        public Nullable<double> QTY { get; set; }
        public string RAF_YERI { get; set; }
        public string CLAIM_TUR { get; set; }
        public string PAY { get; set; }
        public string ORJ { get; set; }
        public string MUH_A { get; set; }
        public string MUH_S { get; set; }
        public string MUH_IADE_S { get; set; }
        public string MUH_IADE_A { get; set; }
        public string MUH_ISK_A { get; set; }
        public string MUH_ISK_S { get; set; }
        public string MUH_KDV_A { get; set; }
        public string MUH_KDV_S { get; set; }
        public string YENI_KOD { get; set; }
        public string YENI_KOD_SON { get; set; }
        public string MUH_GRSAT { get; set; }
        public string MUH_GRSATISK { get; set; }
        public string MODEL_NO { get; set; }
        public Nullable<byte> MERKEZ { get; set; }
        public Nullable<double> MALIYET_ORAN { get; set; }
        public Nullable<short> REKABET { get; set; }
        public string MARKAKOD { get; set; }
        public string ALTGRUP_NO { get; set; }
        public string ISKGRUP { get; set; }
        public Nullable<double> ATILSTK_ISK { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<double> SONALIS_FYT_TL { get; set; }
        public Nullable<double> SONALIS_FYT_DOVIZ { get; set; }
        public string URET_STK_KOD { get; set; }
        public string GARANTI_BELGE { get; set; }
        public string SERITAKIP { get; set; }
    }
}
